# Project
version=1.8.3
group=net.anvian.electricmace
java_version=21

# Common
minecraft_version=1.21.11
mod_name=ElectricMace
mod_author=anvian
mod_id=electricmace
license=GPL-3.0
credits=
description=Adds the possibility of enchanting the new Mace with Channeling so that when we hit a mob from above it will be hit by lightning if it thunders.
minecraft_version_range=[1.21.11, 1.21)
neo_form_version=1.21.11-20251209.172050
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric
fabric_version=0.140.0+1.21.11
fabric_loader_version=0.18.3

# NeoForge
neoforge_version=21.11.10-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

anvianslib_version=1.4