# Project
version=1.7
group=net.anvian.electricmace
java_version=21

# Common
minecraft_version=1.21.2
mod_name=ElectricMace
mod_author=anvian
mod_id=electricmace
license=GPL-3.0
credits=
description=Adds the possibility of enchanting the new Mace with Channeling so that when we hit a mob from above it will be hit by lightning if it thunders.
minecraft_version_range=[1.21.2, 1.21.4)

# Fabric
fabric_version=0.106.1+1.21.2
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.2.1-beta
neoforge_loader_version_range=[,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

anvianslib_version=1.1